// Hình minh hoạ 3D: bộ Microsoft Fluent Emoji (giấy phép MIT — https://github.com/microsoft/fluentui-emoji).
// Đang nạp qua CDN jsDelivr. Muốn chạy không cần mạng (demo bảo vệ): tải các file về public/3d/
// rồi đổi ICON_BASE thành "/3d" — giữ nguyên tên file.
const ICON_BASE = "https://cdn.jsdelivr.net/gh/microsoft/fluentui-emoji@main/assets";

const FILES = {
  trophy: "Trophy/3D/trophy_3d.png",
  books: "Books/3D/books_3d.png",
  robot: "Robot/3D/robot_3d.png",
  gift: "Wrapped gift/3D/wrapped_gift_3d.png",
  abacus: "Abacus/3D/abacus_3d.png",
  ruler: "Straight ruler/3D/straight_ruler_3d.png",
  pencil: "Pencil/3D/pencil_3d.png",
  openBook: "Open book/3D/open_book_3d.png",
  crown: "Crown/3D/crown_3d.png",
  star: "Star/3D/star_3d.png",
  cap: "Graduation cap/3D/graduation_cap_3d.png",
  chart: "Bar chart/3D/bar_chart_3d.png",
  laptop: "Laptop/3D/laptop_3d.png",
  phone: "Mobile phone/3D/mobile_phone_3d.png",
  numbers: "Input numbers/3D/input_numbers_3d.png",
  letters: "Input latin letters/3D/input_latin_letters_3d.png",
  speaker: "Speaker high volume/3D/speaker_high_volume_3d.png",
  target: "Bullseye/3D/bullseye_3d.png",
  medal: "Sports medal/3D/sports_medal_3d.png",
  sunflower: "Sunflower/3D/sunflower_3d.png",
  blossom: "Blossom/3D/blossom_3d.png",
  cloud: "Cloud/3D/cloud_3d.png",
  party: "Party popper/3D/party_popper_3d.png",
  bulb: "Light bulb/3D/light_bulb_3d.png",
  shield: "Shield/3D/shield_3d.png",
  hourglass: "Hourglass done/3D/hourglass_done_3d.png",
  heart: "Red heart/3D/red_heart_3d.png",
  game: "Video game/3D/video_game_3d.png",
  rocket: "Rocket/3D/rocket_3d.png",
  memo: "Memo/3D/memo_3d.png",
  hundred: "Hundred points/3D/hundred_points_3d.png",
  sparkles: "Sparkles/3D/sparkles_3d.png",
  fire: "Fire/3D/fire_3d.png",
  gem: "Gem stone/3D/gem_stone_3d.png",
  calendar: "Spiral calendar/3D/spiral_calendar_3d.png",
  check: "Check mark button/3D/check_mark_button_3d.png",
  lock: "Locked/3D/locked_3d.png",
  brain: "Brain/3D/brain_3d.png",
  chat: "Speech balloon/3D/speech_balloon_3d.png",
  clipboard: "Clipboard/3D/clipboard_3d.png",
  puzzle: "Puzzle piece/3D/puzzle_piece_3d.png",
  glowStar: "Glowing star/3D/glowing_star_3d.png",
  flag: "Flag in hole/3D/flag_in_hole_3d.png",
  chartUp: "Chart increasing/3D/chart_increasing_3d.png",
  cross: "Cross mark/3D/cross_mark_3d.png",
  warning: "Warning/3D/warning_3d.png",
  user: "Bust in silhouette/3D/bust_in_silhouette_3d.png",
  users: "Busts in silhouette/3D/busts_in_silhouette_3d.png",
  info: "Information/3D/information_3d.png",
  key: "Key/3D/key_3d.png",
  newspaper: "Newspaper/3D/newspaper_3d.png",
  muscle: "Flexed biceps/Default/3D/flexed_biceps_3d_default.png",
  clock: "Alarm clock/3D/alarm_clock_3d.png",
  desktop: "Desktop computer/3D/desktop_computer_3d.png",
  sun: "Sun/3D/sun_3d.png",
  shop: "Shopping bags/3D/shopping_bags_3d.png",
  smile: "Grinning face/3D/grinning_face_3d.png",
  shirt: "T-shirt/3D/t-shirt_3d.png",
  pin: "Round pushpin/3D/round_pushpin_3d.png",
  mail: "Envelope/3D/envelope_3d.png",
  question: "Red question mark/3D/red_question_mark_3d.png",
  house: "House/3D/house_3d.png",
  compass: "Compass/3D/compass_3d.png",
  inbox: "Inbox tray/3D/inbox_tray_3d.png",
  package: "Package/3D/package_3d.png",
  video: "Clapper board/3D/clapper_board_3d.png",
  goldMedal: "1st place medal/3D/1st_place_medal_3d.png",
  militaryMedal: "Military medal/3D/military_medal_3d.png",
  scroll: "Scroll/3D/scroll_3d.png",
  notepad: "Spiral notepad/3D/spiral_notepad_3d.png",
  writing: "Writing hand/Default/3D/writing_hand_3d_default.png",
  thumbsUp: "Thumbs up/Default/3D/thumbs_up_3d_default.png",
  thumbsDown: "Thumbs down/Default/3D/thumbs_down_3d_default.png",
  ear: "Ear/Default/3D/ear_3d_default.png",
  camera: "Camera/3D/camera_3d.png",
  hourglassRun: "Hourglass not done/3D/hourglass_not_done_3d.png",
  seedling: "Seedling/3D/seedling_3d.png",
  sunCloud: "Sun behind cloud/3D/sun_behind_cloud_3d.png",
  rainbow: "Rainbow/3D/rainbow_3d.png",
  balloon: "Balloon/3D/balloon_3d.png",
  palette: "Artist palette/3D/artist_palette_3d.png",
  picture: "Framed picture/3D/framed_picture_3d.png",
  label: "Label/3D/label_3d.png",
  ticket: "Ticket/3D/ticket_3d.png",
};

export function Img3D({ name, className = "", style, alt = "" }) {
  return <img src={icon3d(name)} alt={alt} draggable={false} loading="lazy" className={`pointer-events-none select-none object-contain ${className}`} style={style} />;
}

export function icon3d(name) {
  const file = FILES[name];
  return file ? `${ICON_BASE}/${file.split("/").map(encodeURIComponent).join("/")}` : "";
}
